### ISSUE TITLE
nova komponenta: menu vrstica - Kategorije - #1

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#11]
Prosim za oceno dela:
* komponenta: menujska vrstica - s kategorijami
* primer na: https://novice.alpha.najdi.si
* zahteve:
** izgled - taksen, kot je trenutno na Alpha okolju
** meniji imajo lahko tudi subMenije
** meni "Več" vsebuje vse opcije/izbire, ki se trenutno ne morejo prikazati glede na (horizontalno) velikost
** menu opcije se preberejo iz specificnega <ul> elementa
*** potencialno mozna izvedba, da se opcije kot Json_data posredujejo komponenti;
** mora biti UI-resize-able:
*** se pravi z zmanjsevanjem resoulucije/browser_okna .. se menu_opcije -> preselijo -> v pod_opcije izbire "Vec";

Kolikor smo na to temo ze govorili .. je bila ena od predhodnih ocen: cca. 15 ur;

Nujnost: precej nujno;

Alternative:
* predlagajte ..; naceloma pa ne vidim alternative ..

--
.. torej glede menija na najdi.si. Dalce najbolj pametno bi bilo spremenit design. “Vec” ne uporablja skoraj nihce vec in to z dobrim razlogom. V responsive portalih se meni praviloma skrije (primer 24.ur). Druga opcija bi bila, da gre v vec vrstic.

Z react cmp bi bilo mozno doseci tudi tako delovanje, kot bi vidva zelela. Venda to pomeni merjenje sirine portala, render vseh besed v skritem elementu in merjenje njihove sirine. Nato pa js hokus pokus, ki bi vse to preracunal in ustrezno zlozu. Seveda bi bilo potrebno na resize event to vsakic znova merit/racunat ter zlozit.

Ker ze sedaj zaradi neodvisnih cmp dosti prevec merimo, bi to mocno odsvetoval... . 

Ce pa ni druge, bi pa tako cmp ki prek API prejme title/linke, ter se zlozi v tako obliko itd, ocenu na cca 2 dni dela. Morda kaksna ura manj, vendar je dela kar dosti... . 

Se enkrat... ce se le da, dajmo drugace... .
--

**Comment by vajtim** [comment]
Dodana je nova komponenta **showMenu**. 
Potreben array s trenutnim menijem strani http://novice.alpha.najdi.si/ komponenta ze vsebuje. Po potrebi se ga lahko povozi cez prvi parameter.  

Za prikaz pa zadosca: 
`najdisiComponents.showMenu(null, document.getElementById("menu"));

**Comment by bostjans** [comment]
Ok.
A lahko dopolnis se (osnovni) README.md s primeri uporabe .. za menu komponento:
* po IDju ali
* po Json strukturi?

**Comment by markoBlagotinsek** [comment]
Kaj tocno pa podre?

**Comment by bostjans** [comment]
Recimo na Alpha/DEV okolju imas na desni strani eno kopico raznih gradnikov, ki si vertikalno (lepo) sledijo:
* http://novice.alpha.najdi.si/kategorija/slovenija

Ce pa vkljucim novo style.css datoteko dobim -> malo zmedo, oz. se doloceni box-i zacnejo prekrivati ali pa neustrezno prikazovati. Glej sliko ..
-> primer box-a: NAJBOLJ BRANO
![screenshot_2018-07-30 najdi si](https://user-images.githubusercontent.com/577912/43400870-21ece074-940f-11e8-8525-4cada6af43a3.png)

**Comment by markoBlagotinsek** [comment]
Mislim, da mi je jasno kje je problem. Bom preveril.

**Comment by vajtim** [comment]
Readme je posodobljen.
