### ISSUE TITLE
Prikaz strani v IE - #2

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#13]
Prikaz strani v IE : zadnja verzija Edge in IE
= problematicno (!)

Predvsem za komponento: showBoxArticles()

**Comment by markoBlagotinsek** [comment]
Na Edgeu ne vidim odstopanj od chrome verzije. Lahko opises oz. dodas screenshot?

**Comment by wechta** [comment]
Predvsem je problem v ie11.

**Comment by vajtim** [comment]
Sem dodal babel-polyfill, tako da bi morale biti tezave s Promisi v IE11 resene.

**Comment by bostjans** [comment]
Ni reseno. Predvsem komponenta showBoxArticles() se raztegne .. v nedogled;

**Comment by bostjans** [comment]
Tole zgleda reseno. Se v preverjanju/revidiranju ..
