### ISSUE TITLE
najdiSi: komponenta: showNormalArticle() - correction - #2

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#15]
.. razmak med zgornjim robom in prvim tekstom (vir, kategorija, cas objave) ..
.. naj se zmanjsa na: 20px

Zahteva narocnika.

**Comment by markoBlagotinsek** [comment]
Kolikor vidim so razmaki ze na 20px, razen ce se ne razumemo.

**Comment by bostjans** [comment]
.. iz slikce spodaj .. meni kaze, da je top padding = 25; .. naj se zmanjsa ..
![screenshot_2018-08-06a](https://user-images.githubusercontent.com/577912/43701290-e6749054-9955-11e8-8a96-93439648923a.png)

**Comment by bostjans** [comment]
.. tole še ni podelano.

**Comment by vajtim** [comment]
Urejeno.
