### ISSUE TITLE
najdiSi: komponenta: showArticleWithSub() - correction - #2

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#16]
.. velikost Font-a med levim (glavna novica) in desnim (dodatne novice) delom ..
.. naj se spremeni za desni del:
* point je, da zelimo imeti Font v desnem delu manjsi kot v levem

Kot vidim je font-weight: 700 .. v obeh delih.
Naj se v desnem delu zmanjsa na (cca.): 610

Zahteva narocnika.

**Comment by markoBlagotinsek** [comment]
Popravljeno bo na nasledji mozen weight, 500.
