### ISSUE TITLE
najdiSi: komponenta: vse() - dopolni link za kategorijo in vir - #2

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#22]
Komentar od narocnika:
    V prikazu ene novice naj se odpirata linka na kategorijo in vir v istem oknu (trenuto target='_blank'). Govorim o teh veh linkih:
```
..
```

![picture1](https://user-images.githubusercontent.com/577912/44947381-b982d580-ae0c-11e8-8f18-d633e526d098.png)

**Comment by vajtim** [comment]
Urejeno.
