### ISSUE TITLE
najdiSi: komponenta: vse() - fonti - #3

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#23]
Komentar od narocnika:
> Uskladite fonte v elementih na desni s fonti teksta. novic  https://fonts.google.com/specimen/Roboto 
>	Ostaja. V IE font tudi povzroča težave s šumniki. Naj se uporabi latin-ext subset pri nalaganju fonta: https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=latin-ext

```
Naj se uporabi latin-ext subset pri nalaganju fonta:
    https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=latin-ext
```

**Comment by vajtim** [comment]
Urejeno

**Comment by bostjans** [comment]
.. meni zgleda sklano. Pocakam se na feedback narocnika.

**Comment by bostjans** [comment]
Narocnik javil, da neskladnost se vedno obstaja na IE(v11). Vendar se s tem ne bomo ukvarjali trenutno. Done.
