### ISSUE TITLE
najdiSi: performance impact -> measurment - #1

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#25]
Glede na komentar narocnika, da so novejse strani počasnejše ->
-> bi izvedli meritev, da dobimo neke oprijemljive rezultate, kaj pomeni "počasnejše".

Predlog:
* izvedba meritve nalaganja uvodne (index) strani: http://novice.alpha.najdi.si >< http://novice.najdi.si
* izvedba meritve (končnega) prikaza uvodne (index) strani: http://novice.alpha.najdi.si >< http://novice.najdi.si
* + ponovitev istih postopkov brez vpliva reklam (Ads) - recimo, da se izloči iframe + vse kar je povezano z oglasi (če je to mogoče?)

Ker tega jst še nisem izvajal -> me najprej zanima:
* obstajajo za navedene zahteve kakšna orodja/proces?
* še kakšen predlog?

Čas izvedbe:
* čim prej

Note:
* ure za to se normalno pišejo (-> in obračunajo);

**Comment by vajtim** [comment]
Za meritve popolnoma zadoscajo chrome devtools. Predlagal bi, da preletis tole:

https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#overview

Kar se tice vklopa/izklopa Adsov, si instaliraj kak adblocker (jaz uporabljam Adblock Plus).

Kolikor testiram, dela nova stran celo nekoliko hitreje. Imata pa obe ogromna nihanja, zato je zelo tezko delat neko smisleno primerjavo. Casi nalagnja strani namrec nihajo od 1s, pa vse do 30s?! 

Edina povezava z samimi react komponentami je ta, da se le-te zacnejo nalagati po page loadu. Za tem so nalozene instant (slike se nalagajo za tem, kar pa tako ni kaj). Stara stran se pa pac nalaga/prikazuje po kosckih.

Ce bi tole stalo na reactu z vklopljenim server renderingom namesto javi, se na normalni liniji brez slik komot pogovarjamo o desetinkah... .  Se povezava:

https://alligator.io/react/server-side-rendering/

**Comment by bostjans** [comment]
[primerjava_strani.docx](https://github.com/wechta/najdisi/files/2491541/primerjava_strani.docx)
