### ISSUE TITLE
najdiSi: komponenta: novice_dneva = showArticleSwitcher() - CSS - #5

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#27]
Preveri prikaz komponente na: http://novice.alpha.najdi.si/
.. + dopolni glede na komentar narocnika:
```
Naslov novice dneva ima font-size: 20px in line-height: 18px. To povzroča, da je sam naslov med vrsticami "nagužvan". Ko greš z miško čez naslov se prikaže še underline, ki se povsem stika s tekstom v drugi vrstici. Če pa je line-height: 20px (enako kot font-size), je zadeva bolj berljiva.
Na primer, v single news komponenti je font-size: 15px in line-height: 18px. Zadeva je lepo berljiva, ker ima še malo več razmika vmes.
Prilagam še sliko (na vrh line height 18px, spodaj 20 px) -> novica-dneva-line-height.jpg
```

![novica-dneva-line-height](https://user-images.githubusercontent.com/577912/45406282-4f68fc80-b666-11e8-8921-c2bda628f361.jpg)

**Comment by markoBlagotinsek** [comment]
Problem je, da kolikor je men znano, underlined text na hover ni biu v planu. Tako, da mi pls sporoci, a mamo underlined text in dvignem line-height, al ga nimam in nardim mocnejsi selektor. Trenutno bootstrap povozi nas selector, zato se text underlinea.

**Comment by bostjans** [comment]
.. sporocam opcijo: mamo underlined text in dvignem line-height
Javi, ko podelas.

**Comment by markoBlagotinsek** [comment]
Done
