### ISSUE TITLE
najdiSi: splošno/izgled - neustrezen prikaz - #2

### ISSUE THREAD

**Issue by bostjans** [wechta/najdisi#28]
Meni se dogaja, da se stran:
* http://novice.alpha.najdi.si
.. neustrezno prikaze na Chromium browser - Linux - nekako zadnja verzija (Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit));

Neustrezno pomeni:
* ni poravnanih okvirjev
* ni space-ov med posameznimi komponentami
* ..

Starejša verzija Chromium browser-ja .. pa mi deluje ustrezno.

Ali lahko nekdo (od vas) preveri, če ima podobno obnašanje? Pa kaj bi bil razlog?

**Comment by vajtim** [comment]
Sorry, tule ti pa tezko pomagam. 

Sem ceknu na vseh compih, tudi v ubuntu virtualki, pa mi ne uspe reproducirat. Kak caching css issue mogoce? A problem se obstaja, tudi ce nalozis novejso verzijo?

https://www.ubuntuupdates.org/pm/google-chrome-stable
